=== MINQ-Project/mps/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="package">
    <xs:complexType>
      <xs:sequence>
		  
        <xs:element name="meta">
			<xs:complexType>
				<xs:sequence>
					
					<xs:element name="name">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:pattern value="[a-zA-Z_]+" />
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
				
					<xs:element name="description" type="xs:string"></xs:element>
				
					<xs:element name="version">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:pattern value="v(\d\.){2}(\d)" />
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		  
	  <xs:element name="minq" minOccurs="0" maxOccurs="1">
		  <xs:complexType>
			<xs:sequence>
				<xs:element name="file" type="xs:string"></xs:element>
			</xs:sequence>
		  </xs:complexType>
	  </xs:element>

	  <xs:element name="scripts" minOccurs="0">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="script" maxOccurs="unbounded">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="name" use="required">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[a-zA-Z_\-]+" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:attribute>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>


      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== MINQ-Project/mps/package.xml
<?xml version="1.0" encoding="UTF-8"?>
<package xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="./schema.xsd">
    <meta>
		<name>my_app</name>
		<description>My application in minq</description>
		<version>v0.0.1</version>
	</meta>
	<minq>
		<file>index.mq</file>
	</minq>
	<scripts>
		<script name="start">minq index.mq</script>
	</scripts>
</package>
